### ISSUE TITLE
Vectorized points_from_xy?

### ISSUE THREAD

**Issue by ljwolf** [SamComber/spacv#1]
Watching these updates roll in is very exciting :)

I wanted to just make a minor suggestion: the `geopandas.points_from_xy` can be significantly more efficient than the list comprehension + `shapely.geometry.Point()` strategy used here. 

https://github.com/SamComber/spacv/blob/13f6303d871f35abe287ca0df7dc3296de1c71f6/spacv/utils.py#L20

This is mainly because of efficiency gains made using `pygeos`, which vectorizes the creation of the points. I'd use this wherever you're casting from arrays to `geopandas.Geo*` containers.

**Comment by SamComber** [comment]
Thanks and great suggestion, I wasn't aware of this! I can see the performance gains are made from `geopandas` [here](https://github.com/geopandas/geopandas/blob/master/geopandas/_vectorized.py#L235) conditional on `pygeos` being installed.

Will apply this in the next push. As ever, your feedback and review is always welcome.
